name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Define the branch to trigger the workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into server and execute script
        run: |
         ssh -o StrictHostKeyChecking=no ubuntu@34.239.249.201 'bash -s' < ./scripts/deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # - name: executing remote ssh commands using ssh key
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: |
            



