name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Define the branch to trigger the workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:

      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      