name: Deploy Calcom Stack
on:
  workflow_dispatch:
jobs:
  calcom-stack:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Rsync Deployments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu/calcom
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy Calcom Stack
      uses: appleboy/ssh-action@v1.0.3
      with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
           rm -rf calcom-docker
           git clone --recursive https://github.com/calcom/docker.git calcom-docker
           cd calcom-docker && git submodule update --remote --init
           mv .env.example .env
           sed -i "s/^CALENDSO_ENCRYPTION_KEY=.*/CALENDSO_ENCRYPTION_KEY=${{secrets.CALENDSO_ENCRYPTION_KEY}}/" .env
           sed -i "s/^NEXTAUTH_SECRET=.*/NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}}/" .env
           cat .env
           cd ..
           cp ~/calcom/docker-compose.yaml calcom-docker/docker-compose.yaml
          


           

    