name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Define the branch to trigger the workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu/calcom
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
           chmod +x /home/ubuntu/calcom/scripts/deploy.sh
           bash /home/ubuntu/calcom/scripts/deploy.sh
    