name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Define the branch to trigger the workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}