name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Define the branch to trigger the workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      # Step 1: SSH to the remote server and install Docker
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            #curl -o- https://get.docker.com | bash -
            #docker --version
            #docker compose version
            rm -rf sel-hosted-calcom
            git clone https://github.com/zaheerahmad33/sel-hosted-calcom.git
            cd sel-hosted-calcom/nginx-proxy 
            sudo docker compose down
            sudo docker compose up


