name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Define the branch to trigger the workflow
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: SSH to the remote server and install Docker
      - name: SSH to remote server and install Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Docker using curl -o- get.docker.com | bash
            curl -fsSL https://get.docker.com | bash -
